// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

import {FHE, euint32, ebool, eaddress, externalEuint32} from "@fhevm/solidity/lib/FHE.sol";
import {ZamaEthereumConfig} from "@fhevm/solidity/config/ZamaConfig.sol";

/// @title SilentBid — Privacy-preserving sealed-bid auction on Zama FHEVM
/// @notice Bidders submit encrypted bids. The contract maintains the encrypted
///         highest bid and winner using FHE.select. Only the winner is revealed
///         after the auction ends.
contract SilentBid is ZamaEthereumConfig {
    address public owner;
    bool public ended;
    uint256 public endTime;

    euint32 private _highestBid;
    eaddress private _winner;
    uint256 public bidCount;

    event BidSubmitted(address indexed bidder);
    event AuctionEnded(address indexed winner);

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner");
        _;
    }

    modifier auctionActive() {
        require(!ended, "Auction ended");
        require(block.timestamp < endTime, "Auction expired");
        _;
    }

    constructor(uint256 _duration) {
        owner = msg.sender;
        endTime = block.timestamp + _duration;
        // Initialize with trivial zeros (all bids will be higher)
        _highestBid = FHE.asEuint32(0);
        _winner = FHE.asEaddress(address(0));
    }

    /// @notice Submit an encrypted bid. The contract compares it with the
    ///         current highest bid using FHE.gt, then conditionally updates
    ///         both the highest bid and the winner using FHE.select.
    /// @param encryptedBid Client-side encrypted bid amount (externalEuint32)
    /// @param inputProof ZK proof generated by the relayer SDK
    function bid(
        externalEuint32 encryptedBid,
        bytes calldata inputProof
    ) public auctionActive {
        // Verify and decrypt the client-encrypted input
        euint32 newBid = FHE.fromExternal(encryptedBid, inputProof);

        // Compare with current highest bid → encrypted boolean
        ebool isHigher = FHE.gt(newBid, _highestBid);

        // Encrypted conditional updates — no plaintext branches!
        _highestBid = FHE.select(isHigher, newBid, _highestBid);
        eaddress bidderAddr = FHE.asEaddress(msg.sender);
        _winner = FHE.select(isHigher, bidderAddr, _winner);

        bidCount++;
        emit BidSubmitted(msg.sender);
    }

    /// @notice End the auction and grant decryption permissions.
    ///         Can be called by owner at any time, or by anyone after endTime.
    function endAuction() public {
        require(!ended, "Already ended");
        require(
            block.timestamp >= endTime || msg.sender == owner,
            "Too early"
        );
        ended = true;

        // Grant decryption so relayer can reveal results
        FHE.allowThis(_highestBid);
        FHE.allowThis(_winner);

        // Also allow the owner to decrypt
        FHE.allow(_highestBid, owner);
        FHE.allow(_winner, owner);

        emit AuctionEnded(msg.sender);
    }

    /// @notice Allow a specific user to decrypt the highest bid
    function allowBidDecryption(address user) public {
        FHE.allow(_highestBid, user);
    }

    /// @notice Allow a specific user to decrypt the winner
    function allowWinnerDecryption(address user) public {
        FHE.allow(_winner, user);
    }

    // --- Getters ---

    function getHighestBid() public view returns (euint32) {
        return _highestBid;
    }

    function getWinner() public view returns (eaddress) {
        return _winner;
    }

    /// @notice Check if auction is active
    function isActive() public view returns (bool) {
        return !ended && block.timestamp < endTime;
    }

    // --- Test helpers (trivial encrypt, for local testing only) ---

    /// @dev Test-only: submit a bid using trivial encryption (not secure in production)
    function bidTrivial(uint32 plainBid) public auctionActive {
        euint32 newBid = FHE.asEuint32(plainBid);
        ebool isHigher = FHE.gt(newBid, _highestBid);
        _highestBid = FHE.select(isHigher, newBid, _highestBid);
        eaddress bidderAddr = FHE.asEaddress(msg.sender);
        _winner = FHE.select(isHigher, bidderAddr, _winner);
        bidCount++;
        emit BidSubmitted(msg.sender);
    }
}
